'use client';
import {useState} from 'react';
import {ArrowRight,ArrowUpRight,ArrowLeft,Route,CarFront,Clock3,Users,Check,MapPin,CalendarDays} from 'lucide-react';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
type Offer={name:string;car:string;price:number;initials:string;capacity:number};
const offers:Offer[]=[{name:'Rafael Martins',car:'Toyota Corolla',price:480,initials:'RM',capacity:4},{name:'Camila Oliveira',car:'Nissan Sentra',price:450,initials:'CO',capacity:4},{name:'André Santos',car:'Chevrolet Spin',price:560,initials:'AS',capacity:6}];
const money=(v:number)=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0});
export default function Home(){
const [view,V]=useState('new'),[step,S]=useState(1),[mode,M]=useState('wait'),[error,E]=useState(''),[selected,O]=useState<Offer|null>(null),[confirmed,C]=useState(false),[sent,Q]=useState(false),[price,P]=useState('470');
const [trip,T]=useState({origin:'Pinheiros, São Paulo',destination:'Allianz Parque, São Paulo',date:'2026-10-17',departure:'18:00',returnDate:'2026-10-18',returnTime:'02:00',people:'4',budget:'450',notes:''});
const field=(label:string,key:keyof typeof trip,type='text')=><label className="field">{label}<input type={type} value={trip[key]} min={type==='number'?'1':undefined} max={key==='people'?'6':undefined} required={key!=='budget'&&key!=='notes'} onChange={e=>T({...trip,[key]:e.target.value})}/></label>;
function next(){E('');if(!trip.origin.trim()||!trip.destination.trim()||trip.origin.trim()===trip.destination.trim())return E('Informe uma origem e um destino diferentes.');if(new Date(`${trip.returnDate}T${trip.returnTime}`)<=new Date(`${trip.date}T${trip.departure}`))return E('O retorno precisa acontecer depois da saída.');if(step===1)S(2);else V('offers');}
const summary=<aside className="summary"><span className="eyebrow">SEU PRÓXIMO DESTINO</span><h2>Os planos são seus.<br/><em>A volta, combinada.</em></h2><div className="route"><div><i/><small>SAÍDA</small><strong>{trip.origin||'Defina a origem'}</strong></div><div><i/><small>DESTINO</small><strong>{trip.destination||'Defina o destino'}</strong></div></div><p><CalendarDays size={18}/>{trip.date.split('-').reverse().join('/')} · {trip.departure}</p><p><Users size={18}/>{trip.people} passageiros</p><p><Clock3 size={18}/>Retorno {trip.returnDate.split('-').reverse().slice(0,2).join('/')} às {trip.returnTime}</p><div className="summary-bottom"><Check size={18}/>{mode==='wait'?'Motorista à disposição no evento':'Motorista retorna no horário combinado'}</div></aside>;
return <><header><button className="brand" onClick={()=>V('new')}><span className="brand-icon"><Route size={24}/></span>link<span>drive</span><b>●</b></button><nav aria-label="Principal"><button className={['new','offers','detail'].includes(view)?'active':''} onClick={()=>V('new')}>Planejar viagem</button><button className={view==='trips'?'active':''} onClick={()=>V('trips')}>Minhas viagens</button></nav><button className="driver-link" onClick={()=>V(view==='driver'?'new':'driver')}><CarFront size={18}/>{view==='driver'?'Área do passageiro':'Área do motorista'}<ArrowUpRight size={16}/></button></header><div className="demo"><i/>Protótipo demonstrativo · Pessoas, propostas e reservas fictícias. Sem pagamentos reais.</div><main><div className="topline"><span>IDA E VOLTA, DO SEU JEITO</span><span><MapPin size={14}/>São Paulo · região de exemplo</span></div>
{view==='new'&&<><div className="heading"><h1>Para onde vamos?</h1><p>Conte seus planos. Receba propostas e escolha com quem ir.</p></div><div className="workspace"><section className="panel"><div className="steps"><span className={step===1?'current':''}><b>1</b>Sua viagem</span><i/><span className={step===2?'current':''}><b>2</b>Detalhes e revisão</span></div><form onSubmit={e=>{e.preventDefault();next()}}>{step===1?<><h2><Route size={21}/>Vamos combinar o percurso</h2><div className="fields">{field('De onde vocês vão sair?','origin')}{field('Qual é o destino?','destination')}</div><div className="grid2">{field('Data de ida','date','date')}{field('Horário de saída','departure','time')}{field('Data de volta','returnDate','date')}{field('Horário de retorno','returnTime','time')}{field('Quantidade de passageiros','people','number')}<div className="hint"><Users size={20}/>Um preço para o grupo inteiro.</div></div></>:<><h2><Clock3 size={21}/>Como será a espera?</h2><RadioGroup value={mode} onValueChange={v=>M(String(v))} className="options"><label htmlFor="wait" className={'option '+(mode==='wait'?'chosen':'')}><RadioGroupItem id="wait" value="wait" aria-label="À disposição durante o evento"/><span><strong>À disposição durante o evento</strong><small>O motorista reserva esse período para seu grupo.</small></span></label><label htmlFor="return" className={'option '+(mode==='return'?'chosen':'')}><RadioGroupItem id="return" value="return" aria-label="Retorno no horário combinado"/><span><strong>Retorno no horário combinado</strong><small>O motorista fica livre entre a ida e a volta.</small></span></label></RadioGroup><div className="fields">{field('Orçamento para o grupo (R$) · opcional','budget','number')}<label className="field">Algo que o motorista precisa saber?<textarea value={trip.notes} onChange={e=>T({...trip,notes:e.target.value})} placeholder="Bagagens, paradas, acessibilidade..."/></label></div><p className="note">O orçamento é uma sugestão. Cada motorista define sua proposta e as condições de espera.</p></>}{error&&<p className="error" role="alert">{error}</p>}<div className="form-bottom">{step===2?<button type="button" className="text-button" onClick={()=>S(1)}><ArrowLeft size={16}/>Voltar</button>:<small>Sem compromisso nesta etapa</small>}<button type="submit" className="primary">{step===1?'Continuar':'Publicar pedido de exemplo'}<ArrowRight size={18}/></button></div></form></section>{summary}</div></>}
{view==='offers'&&<><div className="heading"><h1>Escolha com quem ir.</h1><p>Compare o pacote completo. Estas propostas são exemplos para testar o fluxo.</p></div><div className="workspace"><section><button className="text-button back" onClick={()=>{V('new');S(1)}}><ArrowLeft size={16}/>Editar pedido</button>{offers.filter(o=>o.capacity>=Number(trip.people)).map((o,i)=><article className="offer" key={o.name}><div className="offer-top"><div className="avatar">{o.initials}</div><div><h2>{o.name}</h2><p>{o.car} · {o.capacity} passageiros</p></div><span className="tag">Perfil fictício</span></div><div className="offer-info"><span><Clock3 size={16}/>{mode==='wait'?'Espera incluída no período':'Ida e retorno agendados'}</span><span><Check size={16}/>Pedágios incluídos</span></div><div className="offer-bottom"><div><small>Total para o grupo</small><strong>{money(o.price)}</strong></div><button className={i===0?'primary':'secondary'} onClick={()=>{O(o);V('detail')}}>Ver proposta<ArrowUpRight size={17}/></button></div></article>)}</section>{summary}</div></>}
{view==='detail'&&selected&&<><div className="heading"><button className="text-button" onClick={()=>V('offers')}><ArrowLeft size={16}/>Todas as propostas</button><h1>Antes de combinar, confira.</h1><p>Os detalhes da proposta de {selected.name}.</p></div><div className="workspace"><section className="panel"><div className="offer-top"><div className="avatar">{selected.initials}</div><div><h2>{selected.name}</h2><p>{selected.car} · perfil fictício</p></div></div><dl className="details">{[['Serviço','Ida e volta para '+trip.people+' passageiros'],['Disponibilidade',mode==='wait'?'À disposição durante o período':'Retorno no horário combinado'],['Pedágios','Incluídos'],['Estacionamento','À parte, pago pelo passageiro'],['Hora adicional','R$ 60, mediante acordo'],['Cancelamento de exemplo','Sem cobrança até 24h antes da saída'],['Observações',trip.notes||'Nenhuma observação'],['Preço total',money(selected.price)],['Taxa da plataforma','R$ 0 neste protótipo']].map(([a,b])=><div key={a}><dt>{a}</dt><dd>{b}</dd></div>)}</dl><p className="note">Esta confirmação simula uma reserva. Não contrata um motorista nem gera cobrança.</p><button className="primary full" onClick={()=>{C(true);V('trips')}}>Confirmar reserva de exemplo<Check size={18}/></button></section>{summary}</div></>}
{view==='trips'&&<><div className="heading"><h1>Minhas viagens</h1><p>Seu próximo encontro começa por aqui.</p></div>{confirmed&&selected?<section className="panel booking"><span className="tag green"><Check size={15}/>Reserva simulada confirmada</span><h2>{trip.destination}</h2><p>{trip.date.split('-').reverse().join('/')} · {trip.departure} → retorno {trip.returnTime}</p><div className="offer-top"><div className="avatar">{selected.initials}</div><div><h3>{selected.name}</h3><p>{selected.car}</p></div><strong>{money(selected.price)}</strong></div><p className="note">Não há motorista real aguardando. A reserva existe apenas enquanto esta página estiver aberta.</p><button className="secondary" onClick={()=>{C(false);S(1);V('new')}}>Encerrar simulação e criar novo pedido</button></section>:<section className="panel empty"><CalendarDays size={36}/><h2>Seus próximos planos cabem aqui.</h2><p>Você ainda não confirmou uma reserva de exemplo.</p><button className="primary" onClick={()=>V('new')}>Planejar viagem<ArrowRight size={17}/></button></section>}</>}
{view==='driver'&&<><div className="heading"><h1>Seu tempo. Sua proposta.</h1><p>Explore um pedido de exemplo e monte seu orçamento.</p></div><div className="workspace"><section className="panel"><span className="tag">Pedido demonstrativo</span><h2 className="driver-title">{trip.origin} → {trip.destination}</h2><p>{trip.people} passageiros · {mode==='wait'?'Disponibilidade durante o evento':'Retorno agendado'}</p><form onSubmit={e=>{e.preventDefault();Q(true)}}><label className="field price-field">Sua proposta total para o grupo (R$)<input type="number" min="1" required value={price} onChange={e=>{P(e.target.value);Q(false)}}/></label><p className="note">Neste exemplo: pedágios incluídos, estacionamento à parte e hora adicional de R$ 60. Nenhuma proposta é enviada a uma pessoa real.</p>{sent?<output className="success"><Check size={20}/>Proposta de {money(Number(price))} enviada na simulação.</output>:<button className="primary" type="submit">Simular envio da proposta<ArrowRight size={18}/></button>}</form></section>{summary}</div></>}
<footer><strong>linkdrive</strong><span>Conexões para ir. Combinações para voltar.</span><span>Ambiente de demonstração</span></footer></main></>;
}

